name: 'n3'
data-dir: /Users/sarthakbhat/cluster1/n3
listen-peer-urls: http://192.168.1.25:2582
listen-client-urls: http://localhost:2381,http://192.168.1.25:2381
initial-advertise-peer-urls: http://192.168.1.25:2582
advertise-client-urls: http://192.168.1.25:2381
initial-cluster: n1=http://192.168.1.25:2580,n2=http://192.168.1.25:2581,n3=http://192.168.1.25:2582
initial-cluster-token: etcd-cluster-1
initial-cluster-state: new
